bookmall:
  datasource:
    driver-class-name: org.postgresql.Driver
    host: localhost
    port: 5432
    database: bookmall
    username: postgres
    password: pgsql

spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 10
